top_srcdir   = /home/osnapdev/OSNAP/httpd-2.4.25
top_builddir = /home/osnapdev/OSNAP/httpd-2.4.25
srcdir       = /home/osnapdev/OSNAP/httpd-2.4.25/modules/aaa
builddir     = /home/osnapdev/OSNAP/httpd-2.4.25/modules/aaa
VPATH        = /home/osnapdev/OSNAP/httpd-2.4.25/modules/aaa

include $(top_srcdir)/build/special.mk

