top_srcdir   = /home/osnapdev/OSNAP/httpd-2.4.25
top_builddir = /home/osnapdev/OSNAP/httpd-2.4.25
srcdir       = /home/osnapdev/OSNAP/httpd-2.4.25/modules/http
builddir     = /home/osnapdev/OSNAP/httpd-2.4.25/modules/http
VPATH        = /home/osnapdev/OSNAP/httpd-2.4.25/modules/http

include $(top_srcdir)/build/special.mk

